### ISSUE TITLE
bracey error: <urlopen error [Errno 111] Connection refused>

### ISSUE THREAD

**Issue by aasutossh** [turbio/bracey.vim#21]
I am getting the `Errno 111` error. It starts the server, launches page in browser then server closes or something.
Not all the time but from time to time.

**Comment by Sorvereign** [comment]
I have the same problem, always that i run Bracey i got the same problem.

**Comment by palhiman** [comment]
change into the plugins installation directory. This is different for every plugin manager but should be something like
     1.   `cd ~/.vim/bundle/bracey.vim` for pathogen/neoBundle/vundle
        `cd ~/.vim/plugged/bracey.vim` for plug
    2. `run npm install --prefix server`

**Comment by cjnucette** [comment]
@palhiman:  Nop, I tried that. I didn't work.

**Comment by cjnucette** [comment]
I did the following tests:
1. created a `html` file with a h1, and an empty `css` file. - it fails when you try to open the `css` file.
2. Same `html` with some styles in the `css`file. It works.
3. Same `html` with custom properties `--some-property`. - it fails when you try to open the `css` file.

I hope this helps narrowing down the bug. I really like this plugin.

**Comment by palhiman** [comment]
Bracey only works with html file because server usually responses all other
files such as css, php using html.
Include the css file into html using link tag and run Bracey while u are on
html file.
Try this if nothing happens please let me know....

**Comment by cjnucette** [comment]
@palhiman I didn't say that the `html` was already opened when I did this tests. Sorry, my bad. I launch vim like this `vim index.html` and then I tried to open the `css` file using both `:e` and `gf`if it matters.

**Comment by palhiman** [comment]
I got your point. what you are doing is that after :e style.css (let's
assume) which opens empty css file. Now what happens is that when you don't
write something and exit it without :w
then what is does is it doesn't save it and when you do :w you will get an
empty css file.
Try this and let me know...

**Comment by cjnucette** [comment]
Ok, So I deleted the styles.css file, open index.html, which has a link to styles.css, and run `:Bracey`. Then I open a new file with `:e styles.css`, and immediately get the error. Close without saving. I repeat the same steps but saving the file this time and open it. Again I get an error. Finally I put some rules, save, close, and open the file, and now it works. So if the file doesn't exists, or if the file is empty, or if the file has custom properties, bracey errors.

**Comment by palhiman** [comment]
Did you have `npm` installed. If not then do install it. Let me
know...after that...

**Comment by cjnucette** [comment]
Yes, it is installed. Do you think there is some problem on my end? Don't You have this issue? I'm going to try with a minimal `vimrc` to check.

**Comment by cjnucette** [comment]
Ok, I used the following `vimrc`, and I'm still getting the same error.

```vim
set runtimepath^=~/.config/nvim/plugged/bracey.vim
set runtimepath^=~/.config/nvim/plugged/onedark
filetype plugin indent on
syntax on
set hidden
```

**Comment by turbio** [comment]
I believe this is a bug in the Bracey server. When it encounters a document it can't parse it'll often crash. You should be able to get crash logs from `/tmp/bracey_server_logfile` to help debug why this is happening.

**Comment by cjnucette** [comment]
@turbio hi, in my case when it crashes that file only shows the following:
```
starting bracey with arguments:
port: 5000
web-address: 127.0.0.1
editor-address: 127.0.0.1
```
It did this with both files opened (index.html, style.css) and linked, and the active buffer is the one with index.html.

**Comment by WylliamDias** [comment]
Hi @cjnucette , i had the same problem, i use the "nerdtree" and when i change the buffer i get this error. But what i did to solve it was:
1. Enter in the nerdtree buffer and start Bracey ;
2. In the URL put /name-of-your-html-file (for example http://127.0.0.1:29756/create-point.html).
i hope this will solve your problem.
(sorry about the english, i'm Brazilian)

**Comment by tonyjim02** [comment]
I had this issue when I installed Bracey with VimPlug because I didn't read the part where it says I had to manually install the dependencies so in my case I have Neovim and the bracey plug is installed at ~/.local/share/nvim/plugs/bracey.vim/ once here I proceeded to  run "npm install --prefix server" and wallah it started working as it should and haven't had any issues after.

**Comment by joaocdfarias** [comment]
> I had this issue when I installed Bracey with VimPlug because I didn't read the part where it says I had to manually install the dependencies so in my case I have Neovim and the bracey plug is installed at ~/.local/share/nvim/plugs/bracey.vim/ once here I proceeded to run "npm install --prefix server" and wallah it started working as it should and haven't had any issues after.

Thank you @tonyjim02 this worked really well with me

**Comment by Damian35** [comment]
In my case when I had that problem what I did:
before starting the server I write a basic structure of html and in the css I write something basic, save and then start. excuse my writing.

**Comment by ahmad-shiddiq** [comment]
> I had this issue when I installed Bracey with VimPlug because I didn't read the part where it says I had to manually install the dependencies so in my case I have Neovim and the bracey plug is installed at ~/.local/share/nvim/plugs/bracey.vim/ once here I proceeded to run "npm install --prefix server" and wallah it started working as it should and haven't had any issues after.

Thank you, this works very well :+1:

**Comment by SleepyMario** [comment]
Here another one suffering from this bug. My vim is quite pristine still. Could anyone tell me how to start debugging this? I did correctly follow the installation steps, am not using neovim bbut vim, and am not using nerdtree or anything else (only tried vim-instant-markdown, and tried to disable that, but to no avail). 
error message (random ports leave me with a 'Ranggerror: Maximum call stack size exceeded':

starting server with args "['node', 'launch.js', '--port', '0']"
bracey error: <urlopen error [Errno 111] Connection refused>
bracey error: <urlopen error [Errno 111] Connection refused>
Press ENTER or type command to continue

log:

starting bracey with arguments:
port: 27286
web-address: 127.0.0.1
editor-address: 127.0.0.1
/home/ashwin/.vim/bundle/bracey.vim/server/server.js:87
	var commandArgs = [commandData];
	                  ^

RangeError: Maximum call stack size exceeded
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:87:20)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
starting bracey with arguments:
port: 35129
web-address: 127.0.0.1
editor-address: 127.0.0.1
/home/ashwin/.vim/bundle/bracey.vim/server/server.js:87
	var commandArgs = [commandData];
	                  ^

RangeError: Maximum call stack size exceeded
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:87:20)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
starting bracey with arguments:
port: 35129
web-address: 127.0.0.1
editor-address: 127.0.0.1
/home/ashwin/.vim/bundle/bracey.vim/server/server.js:87
	var commandArgs = [commandData];
	                  ^

RangeError: Maximum call stack size exceeded
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:87:20)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
starting bracey with arguments:
port: 43812
web-address: 127.0.0.1
editor-address: 127.0.0.1
/home/ashwin/.vim/bundle/bracey.vim/server/server.js:87
	var commandArgs = [commandData];
	                  ^

RangeError: Maximum call stack size exceeded
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:87:20)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
starting bracey with arguments:
port: 0
web-address: 127.0.0.1
editor-address: 127.0.0.1
starting bracey with arguments:
port: 1222
web-address: 127.0.0.1
editor-address: 127.0.0.1
/home/ashwin/.vim/bundle/bracey.vim/server/server.js:87
	var commandArgs = [commandData];
	                  ^

RangeError: Maximum call stack size exceeded
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:87:20)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
starting bracey with arguments:
port: 1222
web-address: 127.0.0.1
editor-address: 127.0.0.1
/home/ashwin/.vim/bundle/bracey.vim/server/server.js:87
	var commandArgs = [commandData];
	                  ^

RangeError: Maximum call stack size exceeded
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:87:20)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
starting bracey with arguments:
port: 1222
web-address: 127.0.0.1
editor-address: 127.0.0.1
/home/ashwin/.vim/bundle/bracey.vim/server/server.js:87
	var commandArgs = [commandData];
	                  ^

RangeError: Maximum call stack size exceeded
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:87:20)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
starting bracey with arguments:
port: 467
web-address: 127.0.0.1
editor-address: 127.0.0.1
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 127.0.0.1:467
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at doListen (net.js:1503:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 467
}
starting bracey with arguments:
port: 467
web-address: 127.0.0.1
editor-address: 127.0.0.1
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 127.0.0.1:467
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at doListen (net.js:1503:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 467
}
starting bracey with arguments:
port: 467
web-address: 127.0.0.1
editor-address: 127.0.0.1
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 127.0.0.1:467
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at doListen (net.js:1503:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 467
}
starting bracey with arguments:
port: 0
web-address: 127.0.0.1
editor-address: 127.0.0.1

**Comment by allinu** [comment]
OK，it works，I'm so stupid boy.  i think yarn will be ok, but it doesn' t.

**Comment by 71GA** [comment]
@allinu Your comment is completely useless.

**Comment by allinu** [comment]
@71GA OK,but it's ok for me,sorry cant help you

**Comment by gen4438** [comment]
I have the same problem as @SleepyMario met, when I start the server in a directory which includes non ascii charactors.


> Here another one suffering from this bug. My vim is quite pristine still. Could anyone tell me how to start debugging this? I did correctly follow the installation steps, am not using neovim bbut vim, and am not using nerdtree or anything else (only tried vim-instant-markdown, and tried to disable that, but to no avail).
> error message in vim itself (random ports leave me with a 'Ranggerror: Maximum call stack size exceeded':
> 
> starting server with args "['node', 'launch.js', '--port', '0']"
> bracey error: <urlopen error [Errno 111] Connection refused>
> bracey error: <urlopen error [Errno 111] Connection refused>
> Press ENTER or type command to continue
> 
> log:
> 
> starting bracey with arguments:
> port: 27286
> web-address: 127.0.0.1
> editor-address: 127.0.0.1
> /home/ashwin/.vim/bundle/bracey.vim/server/server.js:87
> var commandArgs = [commandData];
> ^
> 
> RangeError: Maximum call stack size exceeded
> at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:87:20)
> at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
> at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
> at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
> at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
> at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
> at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
> at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
> at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)
> at Server.parseEditorRequest (/home/ashwin/.vim/bundle/bracey.vim/server/server.js:102:8)

**Comment by apchirinoc** [comment]
Hi everyone!

I just installed Bracey and I'm getting this error. I added the `{'do': 'npm install --prefix server'}` after my Plug line `Plug 'turbio/bracey.vim'`. Then I tried installing manually the npm dependencies by going to `~/.vim/plugged/bracey.vim` and running `npm install --prefix server` but I got the same result. Has anyone figured out this bug?

**Comment by bragmore** [comment]
Hello,
 
I recently experienced this aswell, and I wanted to share my experience.. maybe this could be to any help for someone (hopefully). It seems to be different for everyone.

**Long version:**

What happens if you guys just swap out default local ip (127.0.0.1) with just typing localhost in your browser after Bracey started? and then just keep the portnumber that Bracey starts the server from.

**NOTE! this will only work after u get rid of the error by running npm install --prefix server in your plugin directory where bracey is installed**. For me the error dissapeared but I was redirected to an ip that was still giving me 404 page not found.

The whole {'do': 'npm install --prefix server'} when installing the plugin did not work for me at all. It seems better to run npm install --prefix server in the directory where the plugin is installed instead. This is confirmed by others too get rid of the error, most of the time, so don't completely rely on that.

So for example I see that Bracey starts the server at 127.0.0.1:34003 (port number is always random as stated in the README).
Simply try to replace 127.0.0.1 with localhost, in other words: localhost:34003 or http://localhost:34003

**To get this to work I did the following (using lua config, but should work similarly for vimscript aswell)**

- First install npm install --prefix server in your plugin directory where bracey is installed, forexample it could be: ~/.vim/bundle/bracey.vim or if using neovim it should be somewhere in ~/.local/share/nvim/site , then it depends on what plugin manager you are using.

For me, using packer.nvim since I've configured my nvim in lua, it's cd ~/.local/share/nvim/site/pack/packer/start/bracey.vim
With this your error bracey error: <urlopen error [Errno 111] Connection refused> should be gone atleast.
But you might experience that you are still getting a 404 page not found. First try to change the ipadress to localhost:portnumber that is given from Bracey when starting it via :Bracey 

**Short version:** 

The command I ran was: 

cd ~/.local/share/nvim/site/pack/packer/start/bracey.vim \
  && npm install --prefix server

After that I put this into my nvim config file (mine is called plugins.lua):

- vim.g['bracey_server_allow_remote_connections'] = 1
( same as setting g:bracey_server_allow_remote_connections = 1 in vimscript in your .vimrc or init.vim, whatever you are using )
- vim.g['bracey_server_path'] = 'http://localhost'
( same as setting g:bracey_server_path = 'http://localhost' in your .vimrc or init.vim, whatever you are using )

You can also try to set:

- vim.g['bracey_auto_start_browser'] = 0
as this seems to have work for someone above..
( same as setting g:bracey_auto_start_browser = 0 in vimscript in your .vimrc or init.vim, whatever you are using )

This is the solution that worked for me atleast. I'm on WSL though. Hope it helps someone, as Bracey is simply amazing!

**Comment by fikrinzf** [comment]
> I had this issue when I installed Bracey with VimPlug because I didn't read the part where it says I had to manually install the dependencies so in my case I have Neovim and the bracey plug is installed at ~/.local/share/nvim/plugs/bracey.vim/ once here I proceeded to run "npm install --prefix server" and wallah it started working as it should and haven't had any issues after.

Thank you man, its worked on me

**Comment by 52617365** [comment]
> 

People like you make me smile, you really took the time to write that and it helped me, thank you.

**Comment by 52617365** [comment]
> Hello,
> 
> I recently experienced this aswell, and I wanted to share my experience.. maybe this could be to any help for someone (hopefully). It seems to be different for everyone.
> 
> **Long version:**
> 
> What happens if you guys just swap out default local ip (127.0.0.1) with just typing localhost in your browser after Bracey started? and then just keep the portnumber that Bracey starts the server from.
> 
> **NOTE! this will only work after u get rid of the error by running npm install --prefix server in your plugin directory where bracey is installed**. For me the error dissapeared but I was redirected to an ip that was still giving me 404 page not found.
> 
> The whole {'do': 'npm install --prefix server'} when installing the plugin did not work for me at all. It seems better to run npm install --prefix server in the directory where the plugin is installed instead. This is confirmed by others too get rid of the error, most of the time, so don't completely rely on that.
> 
> So for example I see that Bracey starts the server at 127.0.0.1:34003 (port number is always random as stated in the README). Simply try to replace 127.0.0.1 with localhost, in other words: localhost:34003 or http://localhost:34003
> 
> **To get this to work I did the following (using lua config, but should work similarly for vimscript aswell)**
> 
>     * First install npm install --prefix server in your plugin directory where bracey is installed, forexample it could be: ~/.vim/bundle/bracey.vim or if using neovim it should be somewhere in ~/.local/share/nvim/site , then it depends on what plugin manager you are using.
> 
> 
> For me, using packer.nvim since I've configured my nvim in lua, it's cd ~/.local/share/nvim/site/pack/packer/start/bracey.vim With this your error bracey error: <urlopen error [Errno 111] Connection refused> should be gone atleast. But you might experience that you are still getting a 404 page not found. First try to change the ipadress to localhost:portnumber that is given from Bracey when starting it via :Bracey
> 
> **Short version:**
> 
> The command I ran was:
> 
> cd ~/.local/share/nvim/site/pack/packer/start/bracey.vim && npm install --prefix server
> 
> After that I put this into my nvim config file (mine is called plugins.lua):
> 
>     * vim.g['bracey_server_allow_remote_connections'] = 1
>       ( same as setting g:bracey_server_allow_remote_connections = 1 in vimscript in your .vimrc or init.vim, whatever you are using )
> 
>     * vim.g['bracey_server_path'] = 'http://localhost'
>       ( same as setting g:bracey_server_path = 'http://localhost' in your .vimrc or init.vim, whatever you are using )
> 
> 
> You can also try to set:
> 
>     * vim.g['bracey_auto_start_browser'] = 0
>       as this seems to have work for someone above..
>       ( same as setting g:bracey_auto_start_browser = 0 in vimscript in your .vimrc or init.vim, whatever you are using )
> 
> 
> This is the solution that worked for me atleast. I'm on WSL though. Hope it helps someone, as Bracey is simply amazing!

People like you make me smile, you really took the time to write that and it helped me, thank you.

**Comment by RafagaBlanca** [comment]
Can someone help me, this is my log:(
I already use 'npm install --prefix server'



`Node.js v17.9.0
starting bracey with arguments:
port: 15868
web-address: 127.0.0.1
editor-address: 127.0.0.1
/home/whiteburst/.config/nvim/plugged/bracey.vim/server/htmlfile.js:4
var htmlhint = new HTMLHintClass;
               ^

TypeError: HTMLHintClass is not a constructor
    at Object.<anonymous> (/home/whiteburst/.config/nvim/plugged/bracey.vim/server/htmlfile.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/whiteburst/.config/nvim/plugged/bracey.vim/server/filemanager.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

Node.js v17.9.0`

**Comment by mshdvv** [comment]
I delete Plug 'turbio/bracey.vim'
make a Plug clean
And reinstall whit Plug 'turbio/bracey.vim', {'do': 'npm install --prefix server'}
And it's work for me
I didn't read about javascript dependencies

**Comment by thepenguinthatwants** [comment]
> > Hello,
> > I recently experienced this aswell, and I wanted to share my experience.. maybe this could be to any help for someone (hopefully). It seems to be different for everyone.
> > **Long version:**
> > What happens if you guys just swap out default local ip (127.0.0.1) with just typing localhost in your browser after Bracey started? and then just keep the portnumber that Bracey starts the server from.
> > **NOTE! this will only work after u get rid of the error by running npm install --prefix server in your plugin directory where bracey is installed**. For me the error dissapeared but I was redirected to an ip that was still giving me 404 page not found.
> > The whole {'do': 'npm install --prefix server'} when installing the plugin did not work for me at all. It seems better to run npm install --prefix server in the directory where the plugin is installed instead. This is confirmed by others too get rid of the error, most of the time, so don't completely rely on that.
> > So for example I see that Bracey starts the server at 127.0.0.1:34003 (port number is always random as stated in the README). Simply try to replace 127.0.0.1 with localhost, in other words: localhost:34003 or http://localhost:34003
> > **To get this to work I did the following (using lua config, but should work similarly for vimscript aswell)**
> > ```
> > * First install npm install --prefix server in your plugin directory where bracey is installed, forexample it could be: ~/.vim/bundle/bracey.vim or if using neovim it should be somewhere in ~/.local/share/nvim/site , then it depends on what plugin manager you are using.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For me, using packer.nvim since I've configured my nvim in lua, it's cd ~/.local/share/nvim/site/pack/packer/start/bracey.vim With this your error bracey error: <urlopen error [Errno 111] Connection refused> should be gone atleast. But you might experience that you are still getting a 404 page not found. First try to change the ipadress to localhost:portnumber that is given from Bracey when starting it via :Bracey
> > **Short version:**
> > The command I ran was:
> > cd ~/.local/share/nvim/site/pack/packer/start/bracey.vim && npm install --prefix server
> > After that I put this into my nvim config file (mine is called plugins.lua):
> > ```
> > * vim.g['bracey_server_allow_remote_connections'] = 1
> >   ( same as setting g:bracey_server_allow_remote_connections = 1 in vimscript in your .vimrc or init.vim, whatever you are using )
> > 
> > * vim.g['bracey_server_path'] = 'http://localhost'
> >   ( same as setting g:bracey_server_path = 'http://localhost' in your .vimrc or init.vim, whatever you are using )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can also try to set:
> > ```
> > * vim.g['bracey_auto_start_browser'] = 0
> >   as this seems to have work for someone above..
> >   ( same as setting g:bracey_auto_start_browser = 0 in vimscript in your .vimrc or init.vim, whatever you are using )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is the solution that worked for me atleast. I'm on WSL though. Hope it helps someone, as Bracey is simply amazing!
> 
> People like you make me smile, you really took the time to write that and it helped me, thank you.

Damn I feel like I am so close but still not getting it to work.

```


 ➜ cd ~/.local/share/nvim/site/pack/packer/start/bracey.vim && npm install --prefix server

up to date, audited 255 packages in 868ms

29 packages are looking for funding
  run `npm fund` for details

17 vulnerabilities (4 moderate, 11 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

```

**Comment by pandasoli** [comment]
```zsh
~/.vim/plugged/bracey.vim && npm install --prefix server
```
as @palhiman said worked for me

**Comment by dejianh** [comment]
Do this first:
cd ~/.vim/plugged/bracey.vim && npm install --prefix server
And make sure the html file has not sytax error. Then run bracey. I think the connection error happens when the HTML file can't be parsed correctly.

**Comment by theDahunsiDavid** [comment]
> I had this issue when I installed Bracey with VimPlug because I didn't read the part where it says I had to manually install the dependencies so in my case I have Neovim and the bracey plug is installed at ~/.local/share/nvim/plugs/bracey.vim/ once here I proceeded to run "npm install --prefix server" and wallah it started working as it should and haven't had any issues after.

Thanks @tonyjim02 This worked for me.

**Comment by synovva** [comment]
in all these issues i saw no one was resolving the case where you are are using lazy.nvim plugin manager but i managed to find a solution . Simple  if you are using different config files for plugins like ma then this might sole your issue.
 return{                                                                                                                                          
      "turbio/bracey.vim",                                                                                                                         
      build = "npm install --prefix server",                                                                                                       
  }

**Comment by GioCamellini** [comment]
npm solved that for me: in ~/.vim/bundle/bracey.vim I launched npm install --prefix server and that's what happened

`$ npm install --prefix server
npm warn old lockfile
npm warn old lockfile The package-lock.json file was created with an old version of npm,
npm warn old lockfile so supplemental metadata must be fetched from the registry.
npm warn old lockfile
npm warn old lockfile This is a one-time fix-up, please be patient...
npm warn old lockfile
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated yaeti@0.0.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated har-validator@5.1.3: this library is no longer supported
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated glob@7.1.3: Glob versions prior to v9 are no longer supported
npm warn deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
npm warn deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
npm warn deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

added 254 packages, and audited 255 packages in 10s

29 packages are looking for funding
  run `npm fund` for details

24 vulnerabilities (2 low, 7 moderate, 10 high, 5 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

bash-5.2$ npm audit fix
npm error code ENOLOCK
npm error audit This command requires an existing lockfile.
npm error audit Try creating one first with: npm i --package-lock-only
npm error audit Original error: loadVirtual requires existing shrinkwrap file
npm error A complete log of this run can be found in: /home/gio/.npm/_logs/2025-03-13T01_47_43_195Z-debug-0.log

bash-5.2$ npm i --package-lock-only
npm error code ENOENT
npm error syscall open
npm error path /home/gio/.vim/bundle/bracey.vim/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/gio/.vim/bundle/bracey.vim/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /home/gio/.npm/_logs/2025-03-13T01_48_24_089Z-debug-0.log

bash-5.2$ npm audit fix --force
npm warn using --force Recommended protections disabled.

up to date, audited 1 package in 276ms

found 0 vulnerabilities
`
and now I got bracey up and running on vi with my index.html live on firefox at http://127.0.0.1:39396/index.html.

Cheers.
