### ISSUE TITLE
Blows up with CSS Grid Layout

### ISSUE THREAD

**Issue by jdsutherland** [turbio/bracey.vim#36]
When the CSS file contains [named grid lines](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Layout_using_Named_Grid_Lines), the following stack trace occurs:

```log
/Users/j/.config/nvim/plugged/bracey.vim/server/cssfile.js:15
        var rules = this.parsed.stylesheet.rules;
                                ^

TypeError: Cannot read property 'stylesheet' of undefined
    at CssFile.selectorFromPosition (/Users/j/.config/nvim/plugged/bracey.vim/server/cssfile.js:15:26)
    at Server.handleEditorCommand (/Users/j/.config/nvim/plugged/bracey.vim/server/server.js:187:28)
    at Server.parseEditorRequest (/Users/j/.config/nvim/plugged/bracey.vim/server/server.js:97:7)
    at IncomingMessage.<anonymous> (/Users/j/.config/nvim/plugged/bracey.vim/server/server.js:65:9)
    at IncomingMessage.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

named grid line syntax:
```css
grid-template-columns: [main-start] 1fr [content-start] 1fr [content-end] 1fr [main-end];
```

It looks like this is probably a bug with the [css parser dependency](https://github.com/reworkcss/css): https://github.com/turbio/bracey.vim/blob/e47352a3682e01cc37c272b02b549bdbef778bdc/server/cssfile.js#L59

**Comment by jdsutherland** [comment]
Haven't thoroughly investigated, but looks like I was partially wrong: named grid line syntax causes an error but [fr](https://css-tricks.com/introduction-fr-css-unit/) is what's causing it to blow up. I suspect the css parser hasn't been updated to support grid and there are likely other issues.

**Comment by mirsella** [comment]
i don't know if this is included in "named grid line" but this make it blow up too :
```
:root {
  --primary: #F7CCCC;
  --second: #F12B6B;
  /* etc */ 
}
```

i hope it can be fixed soon :)

**Comment by mirsella** [comment]
i tried to put my statement in a <style> element directly in the index.html and it works, but not in  the .css.
i'll put it here while i'm using bracey and deleting it after.

**Comment by jdsutherland** [comment]
@mirsella your issue isn't related to grid but what both probably have in common is that they're newer CSS additions. It looks like bracey and the css parser library were mostly built prior to 2015, so it's not surprising that new additions to CSS since then are breaking things.

It seems unlikely that this will get fixed in bracey as it doesn't look very active, which makes sense because modern front-end frameworks tend to feature live reloading. I came across this plugin when I starting working through a book on modern css. I think it's still useful for that, but I don't know enough about modern front-end work to know if bracey is still useful.

If someone did want to fix it, I think the [current css parser](https://github.com/reworkcss/css) (looks dead) would need to swapped out for https://github.com/postcss/postcss.

**Comment by mirsella** [comment]
i've found this project which will replace bracey for me. can even be install as vim module with Plug etc pretty easily.

I know you deleted it from your comments, but what the live reloading feature modern framework have ? like vuejs reactjs etc can have live reload which reload the whole html file so with support for CSS js etc ?

**Comment by jdsutherland** [comment]
@mirsella I replaced the css parser with `postcss`. `postcss` supports CSS3+ features that the old css parser didn't. There is an additional issue, however; `csslint` is used to detect errors and it doesn't support some newer features, notably CSS3 variables. So even though `postcss` works, `csslint` causes bracey to show false positives. 

`csslint` is dead and isn't likely to be updated (see https://github.com/CSSLint/csslint/issues/720).
`stylelint` might be an alternative–I briefly tried swapping it out but couldn't get it working. My workaround is to just remove `csslint` and avoid having Bracey display errors. I'm using CoC with CSS LS, so I have no need for bracey to display errors.

You can try using the branch `postcss-and-remove-csslint` at https://github.com/jdsutherland/bracey.vim if interested. If you do check it out, let me know if you have any issues.

**Comment by mirsella** [comment]
waw gg. when you mentioned that it was the css parser not up to date, I tried to fork it with another one but didn't understand the code. thanks now I'll analyze your fork :)
I'm using live-server now, but thanks.

**Comment by turbio** [comment]
reopening, since linting also needs to be fixed to handle modern css.
