### ISSUE TITLE
Bracey won't start. RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by Loureas** [turbio/bracey.vim#73]
### Problem
Hello! I installed this plugin as instructed in the Neovim with VIM-Plug:
```vim
call plug#begin()
...
Plug 'turbio/bracey.vim', {'do': 'npm install --prefix server'}
...
call plug#end()
```
And after entering this command with an open HTML file Bracey Web Server won't start:
```
:Bracey
starting server with args "['node', 'launch.js', '--port', '18609']"
Press ENTER or type command to continue
```
Browser shows connection reset.
* * *
### Traceback
Bracey Server log file:
```
starting bracey with arguments:
port: 15390
web-address: 127.0.0.1
editor-address: 127.0.0.1
/home/loureas/.local/share/nvim/plugged/bracey.vim/server/server.js:87
        var commandArgs = [commandData];
                          ^

RangeError: Maximum call stack size exceeded
    at Server.parseEditorRequest (/home/loureas/.local/share/nvim/plugged/bracey.vim/server/server.js:87:20)
    at Server.parseEditorRequest (/home/loureas/.local/share/nvim/plugged/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/loureas/.local/share/nvim/plugged/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/loureas/.local/share/nvim/plugged/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/loureas/.local/share/nvim/plugged/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/loureas/.local/share/nvim/plugged/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/loureas/.local/share/nvim/plugged/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/loureas/.local/share/nvim/plugged/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/loureas/.local/share/nvim/plugged/bracey.vim/server/server.js:102:8)
    at Server.parseEditorRequest (/home/loureas/.local/share/nvim/plugged/bracey.vim/server/server.js:102:8)
```
Checkhealth Neovim:
```
coc: health#coc#check
========================================================================
  - OK: nvim version satisfied
  - OK: Environment check passed
  - OK: Javascript bundle build/index.js found
  - OK: Service started

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.15.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 10.2.1 20201203
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - cpp            ✓ ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Other python executable: /usr/sbin/python3
  - INFO: Other python executable: /sbin/python3
  - INFO: Python version: 3.10.7
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v16.15.1
  - WARNING: Missing "neovim" npm (or yarn, pnpm) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
      - Run in shell (if you use pnpm): pnpm install -g neovim
      - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/loureas/.local/state/nvim/lsp.log
  - INFO: Log size: 0 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for cpp: ABI version 14
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for python: ABI version 13
```
Neovim version:
```sh
$ nvim -v
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Features: +acl +iconv +tui
```

**Comment by Svenum** [comment]
Same here
